[package]
name = "git-deploy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive", "env"] }
crossterm = "0.29.0"
git2 = "0.20.2"
octocrab = "0.47.0"
tokio = { version = "1.48.0", features = ["full"] }
